dofile("Tests/bootstrap.lua")
local load_addon = require("Tests.helpers.load_addon")

describe("TraitIndex", function()
	before_each(function()
		load_addon.reset()
		load_addon.load_core()
	end)

	it("builds rows for fixture profession", function()
		local ctx = load_addon.stl().ProfessionContext.GetContextForSkillLine(2881)
		local rows = load_addon.stl().TraitIndex.Build(ctx)
		assert.is_true(#rows >= 4)
	end)
end)

describe("TraitSearch", function()
	before_each(function()
		load_addon.reset()
		load_addon.load_core()
	end)

	it("matches Multicraft through searchableText", function()
		local stl = load_addon.stl()
		local rows = stl.TraitIndex.Build(stl.ProfessionContext.GetContextForSkillLine(2881))
		local filtered = stl.TraitSearch.Filter(rows, { searchText = "multicraft" })
		assert.is_true(#filtered >= 2)
	end)
end)
